### ISSUE TITLE
TypeError (can't dump hash with default proc)

### ISSUE THREAD

**Issue by sushant12** [lynndylanhurley/devise_token_auth#1012]
I generated a access token after logging in from omniauth. I passed those creds in headers to the api and got this issue.

```
Started GET "/test" for 127.0.0.1 at 2017-11-09 15:37:01 +0545
  ActiveRecord::SchemaMigration Load (1.0ms)  SELECT `schema_migrations`.* FROM `schema_migrations`
Processing by Api::EmployeesController#test as */*
  Employee Load (1.2ms)  SELECT  `employees`.* FROM `employees` WHERE `employees`.`uid` = '114481324477582410308' LIMIT 1
  Company Load (1.1ms)  SELECT  `companies`.* FROM `companies` WHERE `companies`.`id` = 1 LIMIT 1
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.13ms)
  Employee Exists (1.3ms)  SELECT  1 AS one FROM `employees` WHERE (`employees`.`uid` = '114481324477582410308' AND `employees`.`id` != 217) LIMIT 1
  Employee Exists (1.6ms)  SELECT  1 AS one FROM `employees` WHERE (`employees`.`uqid` = '6925bd09-7342-4efe-a5cd-c977e997705e' AND `employees`.`id` != 217) LIMIT 1
  Employee Load (1.1ms)  SELECT  `employees`.* FROM `employees` WHERE `employees`.`id` = 217 LIMIT 1
   (0.7ms)  BEGIN
  Employee Exists (2.3ms)  SELECT  1 AS one FROM `employees` WHERE (`employees`.`uid` = '114481324477582410308' AND `employees`.`id` != 217) LIMIT 1
  Employee Exists (1.1ms)  SELECT  1 AS one FROM `employees` WHERE (`employees`.`uqid` = '6925bd09-7342-4efe-a5cd-c977e997705e' AND `employees`.`id` != 217) LIMIT 1
   (1.1ms)  COMMIT
  Company Load (0.9ms)  SELECT  `companies`.* FROM `companies` WHERE `companies`.`id` = 1 LIMIT 1
Completed 200 OK in 226ms (Views: 3.3ms | ActiveRecord: 17.0ms)
** [Raven] can't dump hash with default proc excluded from capture due to environment or should_capture callback

TypeError (can't dump hash with default proc):
  actionpack (4.2.6) lib/action_dispatch/middleware/cookies.rb:414:in `dump'
  actionpack (4.2.6) lib/action_dispatch/middleware/cookies.rb:414:in `serialize'
  actionpack (4.2.6) lib/action_dispatch/middleware/cookies.rb:527:in `[]='
  actionpack (4.2.6) lib/action_dispatch/middleware/session/cookie_store.rb:110:in `set_cookie'
  rack (1.6.4) lib/rack/session/abstract/id.rb:351:in `commit_session'
  rack (1.6.4) lib/rack/session/abstract/id.rb:226:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/flash.rb:260:in `call'
  warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
  warden (1.2.7) lib/warden/manager.rb:35:in `catch'
  warden (1.2.7) lib/warden/manager.rb:35:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  activerecord (4.2.6) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.6) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.6) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.6) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.6) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.6) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
  sentry-raven (2.1.2) lib/raven/integrations/rack.rb:50:in `call'
  rack-mini-profiler (0.9.8) lib/mini_profiler/profiler.rb:282:in `call'
  railties (4.2.6) lib/rails/engine.rb:518:in `call'
  railties (4.2.6) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /home/nikesh/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /home/nikesh/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /home/nikesh/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'


Processing by ExceptionsController#show as */*
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.09ms)
Completed 500 Internal Server Error in 1ms (Views: 0.5ms | ActiveRecord: 0.0ms)

```

Any idea how to fix this?

**Comment by zachfeldman** [comment]
@sushant12 this looks like a problem with the cookies middleware? I don't see devise token auth anywhere in the stack trace.

**Comment by sushant12** [comment]
@zachfeldman  Any tips on how i can debug this?

**Comment by zachfeldman** [comment]
Yeah, what I'm trying to say is that I don't see this library anywhere in your stack trace. It looks to be a problem with `action_dispatch` so have you thought of trying to file a bug over at  https://github.com/rails/rails ?

**Comment by sushant12** [comment]
@zachfeldman actually no i did not consider it but i will. BTW the same issue is persisting for the email and password login too.

**Comment by sushant12** [comment]
closing this since I am following a different approach
