### ISSUE TITLE
BUG:  config.enable_standard_devise_support = true returns wrong current_user

### ISSUE THREAD

**Issue by KelseyDH** [lynndylanhurley/devise_token_auth#1060]
When posting issues, please include the following information to speed up the troubleshooting process:

* **Version**:  0.1.42

Relevant environment:
- Ruby **[2.4.2]**
- Rails **[5.1.4]**
```
    devise (4.3.0)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0, < 5.2)
      responders
      warden (~> 1.2.3)
    devise-i18n (1.5.0)
      devise (>= 3.4)
    devise_token_auth (0.1.42)
      devise (> 3.5.2, <= 4.3)
      rails (< 6)
```

* **Request and response headers**:
Described below.

* **Rails Stacktrace**: this can be found in the `log/development.log` of your API.
* **Environmental Info**: How is your application different from the [reference implementation](https://github.com/lynndylanhurley/devise_token_auth_demo)? This may include (but is not limited to) the following details:
  * **Routes**:

I'm using both `devise` and `devise_token_auth`

```
  namespace :api do |api|
    mount_devise_token_auth_for 'User', at: 'auth'
  end

  as :user do
    # post 'users/password/change', to: 'users/passwords#change', as: 'change_user_password'
    patch 'users/password/change', to: 'users/passwords#change', as: 'change_user_password'
    get 'users/password/check-email', to: 'users/passwords#check_email', as: 'check_email_user_password'
    get 'users/password/reset-success', to: 'users/passwords#reset_success', as: 'reset_success_user_password'
  end


  devise_for :users, skip: :registrations, controllers: {
    confirmations:      'users/confirmations',
    passwords:          'users/passwords',
    # omniauth_callbacks: 'web/users/omniauth_callbacks',
    # registrations:      'users/registrations',
    sessions:           'users/sessions',
  }


```

  * **Gems**:

- `paperTrail` gem, which writes a copy of the Users table over to UserVersion.

  * **Custom Overrides**:  I'm namespacing both devise and devise_token_auth into separate controllers

  * **Custom Frontend**:  iPhone & Android & Postman

## Issue

In my app, my API consumers can switch between child and parent users, with the Bearer token `uid / client / access-token` being the mechanism  issue where my API consumers can switch between users.

However they were complaining about incorrect data being sent back, which I later confirmed to be an issue with `devise_token_auth` after I manually hit two sign_in points with different users.

To replicate.  I created two users with the same password:  

"dojouser17+marge@gmail.com" and "dojouser17+bart@gmail.com"

Next, using devise_token_auth I logged in with the first one 

```
GET api/auth/sign_in
{
	"email": "dojouser17+bart@gmail.com", "password": "That1234"
}
```
receiving back the following headers from Postman in localhost:

```
access-token →z9fS0CuMUZk9_F1FpRY5Tw
cache-control →max-age=0, private, must-revalidate
client →AfYoRq09GaCmATnzAqjAgQ
content-type →application/json; charset=utf-8
etag →W/"1edac4bb16fda94888d87a447cbc0834"
expiry →1516659606
token-type →Bearer
transfer-encoding →chunked
uid →dojouser17+bart@gmail.com
x-content-type-options →nosniff
x-frame-options →SAMEORIGIN
x-request-id →3b1f7b69-03aa-4d54-9911-0aca229d195a
x-runtime →0.217444
x-xss-protection →1; mode=block
```

```
GET api/auth/sign_in
{
	"email": "dojouser17+marge@gmail.com", "password": "That1234"
}

```

receiving back the following headers from Postman in localhost:

```
access-token →4jktXiC-jDG-yMRUboUL2A
cache-control →max-age=0, private, must-revalidate
client →GV1hagOF6CRWIZkvzBHtrA
content-type →application/json; charset=utf-8
etag →W/"aae490494e2e72440f4f0c8273f3dfaf"
expiry →1516660022
token-type →Bearer
transfer-encoding →chunked
uid →dojouser17+marge@gmail.com
x-content-type-options →nosniff
x-frame-options →SAMEORIGIN
x-request-id →ee93f722-3a71-4f9b-bfdf-2408e1d9cec1
x-runtime →0.223127
x-xss-protection →1; mode=block
```

---------------
![screen shot 2018-01-08 at 3 20 48 pm](https://user-images.githubusercontent.com/6710303/34697678-0639e7f8-f489-11e7-8069-9a3c3149aaf9.png)

Next, I copied these headers into two separate requests and hit an app endpoint requiring authentication.  When `config.enable_standard_devise_support` is `true` the api returns back the incorrect current_user for the headers its given, always defaulting to the first user that hit the endpoint.

Attached is a screenshot where you can see `dojouser17+marge@gmail.com` sending a token request, gets back a response with a `current_user` and authentication headers meant for `dojouser17+bart@gmail.com`.

Restarting the server had no effect on this issue. However, the problem went away after I changed `config.enable_standard_devise_support = false`

**Comment by zachfeldman** [comment]
@KelseyDH thanks so much for your report! Seems like a pretty complicated setup. Do you think you could solve this through code/a pull request? If so we'd welcome it!

**Comment by KelseyDH** [comment]
@zachfeldman  I definitely have a hacky setup for my routes, [which came from trying to create a web-accessible endpoint with classic devise to support password resets](https://github.com/lynndylanhurley/devise_token_auth/issues/604#issuecomment-351180401).

It's not an arrangement I'm all that happy with.  E.g. one problem is that despite my attempted solution of trying to subclass ApplicationController into separate standard `devise` web ( `ApplicationController::Base`) and `devise_token_auth` api endpoints (`ApplicationController::Api`), my `devise_token_auth` controller `api/auth` route endpoints for authentication still hit `ApplicationController::Base` (meaning it engages with Rails session, cookies and CSRF protections intended only for my web endpoint used for password resets)... and I suspect this combination of `devise_token_auth` hitting ActionController::Base, along with `DeviseTokenAuth.enable_standard_devise_support = true` invocation of warden methods could be behind what's causing the bug.

**Comment by maltem-za** [comment]
@KelseyDH You may want to check out [this issue](https://github.com/lynndylanhurley/devise_token_auth/issues/375) (see my comment at the bottom), its related issues, and also [this one](https://github.com/lynndylanhurley/devise_token_auth/issues/398).

We had the same symptoms that you are describing, and turning off `config.enable_standard_devise_support` also "fixed" it for us, but it wasn't the root cause.

**Comment by amruthanarayanr** [comment]
I recently started setting up `devise_token_auth` for an existing application which has `devise`. I can confirm what @KelseyDH has mentioned in above comment still exists. I am not using any other devise_token_auth UI libraries. 

>Consequently I strongly suspect there is an issue with DeviseTokenAuth.enable_standard_devise_support, such as in the way it gets invoked within set_user_by_token

In addition to wrong `current_user` thingy, When I try to create/destroy sessions via web (which should go through `devise)`, I see following error (whenever a user tries to sign-in or sign-out):
```
ArgumentError in Devise::SessionsController#destroy

devise (4.3.0) app/controllers/devise_controller.rb:47:in `resource_class'
devise_token_auth (0.2.0) app/controllers/devise_token_auth/concerns/set_user_by_token.rb:41:in `set_user_by_token'

```

The line 41 in `set_user_by_token`, corresponds to the invocation of `resource_class` by providing the `mapping` argument.

https://github.com/plataformatec/devise/blob/715192a7709a4c02127afb067e66230061b82cf2/app/controllers/devise_controller.rb#L49

which actually doesn't take any argument.

----------------------------------

Side note: Thank you for developing this gem.

**Comment by sujaysudheenda** [comment]
I recently started setting up `devise_token_auth` for an existing application which has `devise`. I can confirm what @KelseyDH has mentioned in above comment still exists. I am not using any other devise_token_auth UI libraries. 

>Consequently I strongly suspect there is an issue with DeviseTokenAuth.enable_standard_devise_support, such as in the way it gets invoked within set_user_by_token

In addition to wrong `current_user` thingy, When I try to create/destroy sessions via web (which should go through `devise)`, I see following error (whenever a user tries to sign-in or sign-out):
```
ArgumentError in Devise::SessionsController#destroy

devise (4.3.0) app/controllers/devise_controller.rb:47:in `resource_class'
devise_token_auth (0.2.0) app/controllers/devise_token_auth/concerns/set_user_by_token.rb:41:in `set_user_by_token'

```

The line 41 in `set_user_by_token`, corresponds to the invocation of `resource_class` by providing the `mapping` argument.

https://github.com/plataformatec/devise/blob/715192a7709a4c02127afb067e66230061b82cf2/app/controllers/devise_controller.rb#L49

which actually doesn't take any argument.

----------------------------------

Side note: Thank you for developing this gem.
