### ISSUE TITLE
Devise dependency: Syntax error on Ruby 2.5.0

### ISSUE THREAD

**Issue by nesteves** [lynndylanhurley/devise_token_auth#1076]
Hi!

I ran into this issue with versions 0.1.42 and 0.1.43.beta1 on a rails 5.1.4 application, running with ruby 2.5.0. It results from an exception thrown within the `devise` gem, which has been fixed since version 4.4.0 plataformatec/devise#4736, which lies outside of the version range specified in `devise_token_auth.gemspec`.

The stack trace was:

```ruby
/<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:476:in `load': /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/devise-4.3.0/app/controllers/devise/sessions_controller.rb:5: syntax error, unexpected '{', expecting keyword_end
...ion only: [:create, :destroy] { request.env["devise.skip_tim...
...                              ^
/<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/devise-4.3.0/app/controllers/devise/sessions_controller.rb:5: syntax error, unexpected '}', expecting keyword_end
..."devise.skip_timeout"] = true }
...                              ^ (SyntaxError)
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:476:in `block in load_file'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:661:in `new_constants_in'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:475:in `load_file'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:374:in `block in require_or_load'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:36:in `block in load_interlock'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:11:in `loading'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:36:in `load_interlock'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:357:in `require_or_load'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:335:in `depend_on'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:251:in `require_dependency'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.4/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.4/lib/rails/engine.rb:475:in `each'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.4/lib/rails/engine.rb:475:in `block in eager_load!'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.4/lib/rails/engine.rb:473:in `each'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.4/lib/rails/engine.rb:473:in `eager_load!'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.4/lib/rails/engine.rb:354:in `eager_load!'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.4/lib/rails/application/finisher.rb:67:in `each'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.4/lib/rails/application/finisher.rb:67:in `block in <module:Finisher>'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `call'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
	from /<snip>/workspace/gim-api/project/config/environment.rb:7:in `<top (required)>'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:102:in `preload'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /<snip>/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from -e:1:in `<main>'
```

**Comment by nesteves** [comment]
Thanks for the feedback @zachfeldman. I'll look into it. Here's what I'm planning to do:

* Fork the gem (going from the beta version), change the devise dependency and run the test suite
* Set up a rails-api with the forked version and a generic user model
* Test the endpoints to see if any other errors turn up

Feel free to add or suggest alternatives, I have never contributed to widely used projects such as this one.

Cheers

**Comment by lynndylanhurley** [comment]
@zachfeldman I've been working on a vanilla js reference client that I'd like to use for end-to-end integration testing. I'm building a suite of tools around the client that will help with testing when cutting releases. This will speed up the release cycle.

I'll post a link when it's live, hopefully early next week.

**Comment by develop-test1** [comment]
Hey!
We're run into the same issue today. :)

**Comment by zachfeldman** [comment]
@develop-test1 maybe collab with @nesteves on their work?

**Comment by rinoldsimon** [comment]
The issue still exists
```
ruby (2.5.3)
devise_token_auth (0.1.42)
```
