### ISSUE TITLE
FrozenError (can't modify frozen Hash)

### ISSUE THREAD

**Issue by typhoon2099** [lynndylanhurley/devise_token_auth#1151]
I'm getting the following error in my development environment (Using Ruby 2.5, Rails 5.1.5, and devise_token_auth 0.1.43). This may be related to issue #515:

```
FrozenError (can't modify frozen Hash):
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/2.5.0/delegate.rb:349:in `merge!'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/2.5.0/delegate.rb:349:in `block in delegating_block'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/devise_token_auth-0.1.43/app/controllers/devise_token_auth/concerns/set_user_by_token.rb:148:in `block (2 levels) in update_auth_header'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5/lib/active_record/locking/pessimistic.rb:81:in `block in with_lock'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5/lib/active_record/transactions.rb:210:in `transaction'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5/lib/active_record/transactions.rb:299:in `transaction'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5/lib/active_record/locking/pessimistic.rb:79:in `with_lock'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/devise_token_auth-0.1.43/app/controllers/devise_token_auth/concerns/set_user_by_token.rb:118:in `block in update_auth_header'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/devise_token_auth-0.1.43/app/controllers/devise_token_auth/concerns/set_user_by_token.rb:30:in `ensure_pristine_resource'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/devise_token_auth-0.1.43/app/controllers/devise_token_auth/concerns/set_user_by_token.rb:115:in `update_auth_header'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:413:in `block in make_lambda'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:246:in `block in halting'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:511:in `block in invoke_after'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:511:in `each'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:511:in `invoke_after'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:132:in `run_callbacks'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.5/lib/abstract_controller/callbacks.rb:19:in `process_action'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.5/lib/action_controller/metal/rescue.rb:20:in `process_action'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.5/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/notifications.rb:166:in `block in instrument'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/notifications.rb:166:in `instrument'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.5/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.5/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.5/lib/abstract_controller/base.rb:124:in `process'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionview-5.1.5/lib/action_view/rendering.rb:30:in `process'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.5/lib/action_controller/metal/live.rb:253:in `block (2 levels) in process'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/dependencies/interlock.rb:40:in `block in running'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/concurrency/share_lock.rb:160:in `sharing'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/dependencies/interlock.rb:39:in `running'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.5/lib/action_controller/metal/live.rb:245:in `block in process'
/home/vagrant/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.5/lib/action_controller/metal/live.rb:289:in `block in new_controller_thread'
```

**Comment by Fjool** [comment]
Still happening with Ruby 2.5.1

**Comment by MaicolBen** [comment]
@typhoon2099 can you tell me the action dispatched? It seems to me that happens after an account destroy or something

**Comment by typhoon2099** [comment]
I'm not sure what the specific action is but here's a stack trace of the error:

```
FrozenError (can't modify frozen Hash):
  /usr/local/lib/ruby/2.5.0/delegate.rb:349:in `merge!'
  /usr/local/lib/ruby/2.5.0/delegate.rb:349:in `block in delegating_block'
  /usr/local/bundle/gems/devise_token_auth-0.1.43/app/controllers/devise_token_auth/concerns/set_user_by_token.rb:148:in `block (2 levels) in update_auth_header'
  /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/locking/pessimistic.rb:84:in `block in with_lock'
  /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `block in transaction'
  /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:230:in `block in within_new_transaction'
  /usr/local/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
  /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:227:in `within_new_transaction'
  /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `transaction'
  /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/transactions.rb:212:in `transaction'
  /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/transactions.rb:301:in `transaction'
  /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/locking/pessimistic.rb:82:in `with_lock'
  /usr/local/bundle/gems/devise_token_auth-0.1.43/app/controllers/devise_token_auth/concerns/set_user_by_token.rb:118:in `block in update_auth_header'
  /usr/local/bundle/gems/devise_token_auth-0.1.43/app/controllers/devise_token_auth/concerns/set_user_by_token.rb:30:in `ensure_pristine_resource'
  /usr/local/bundle/gems/devise_token_auth-0.1.43/app/controllers/devise_token_auth/concerns/set_user_by_token.rb:115:in `update_auth_header'
  /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:426:in `block in make_lambda'
  /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:247:in `block in halting'
  /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:517:in `block in invoke_after'
  /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:517:in `each'
  /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:517:in `invoke_after'
  /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:133:in `run_callbacks'
  /usr/local/bundle/gems/actionpack-5.2.0/lib/abstract_controller/callbacks.rb:41:in `process_action'
  /usr/local/bundle/gems/actionpack-5.2.0/lib/action_controller/metal/rescue.rb:22:in `process_action'
  /usr/local/bundle/gems/actionpack-5.2.0/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
  /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `block in instrument'
  /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
  /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `instrument'
  /usr/local/bundle/gems/actionpack-5.2.0/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
  /usr/local/bundle/gems/actionpack-5.2.0/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
  /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
  /usr/local/bundle/gems/actionpack-5.2.0/lib/abstract_controller/base.rb:134:in `process'
  /usr/local/bundle/gems/actionview-5.2.0/lib/action_view/rendering.rb:32:in `process'
  /usr/local/bundle/gems/actionpack-5.2.0/lib/action_controller/metal/live.rb:255:in `block (2 levels) in process'
  /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:42:in `block in running'
  /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:162:in `sharing'
  /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:41:in `running'
  /usr/local/bundle/gems/actionpack-5.2.0/lib/action_controller/metal/live.rb:247:in `block in process'
  /usr/local/bundle/gems/actionpack-5.2.0/lib/action_controller/metal/live.rb:291:in `block in new_controller_thread'
```

Looks like it's the Auth header refreshing that's the issue.
