### ISSUE TITLE
Version 0.2.0 and @latest reintroduces issue of missing :confirm_success_url and unknown attribute 'confirm_success_url' for User. 

### ISSUE THREAD

**Issue by lordkiz** [lynndylanhurley/devise_token_auth#1207]
As reported for older versions [here](https://github.com/lynndylanhurley/devise_token_auth/issues/241#issuecomment-102859088)

Version 0.1.43 works fine.

**Comment by MaicolBen** [comment]
0.2.0 is just a temp version for some people that wanted a feature back, we aren't support it anymore. The title shows a different error than the one you linked. The error is shown to you so you can fix the error, did you set the confirm_success_url? Otherwise when the user clicks in the confirmation mail won't know where to go.

**Comment by lordkiz** [comment]
Yes. In version 0.2.0 setting the confirm_success_url throws the error: `Unknown attribute: confirm_success_url for User` . And not setting it throws the `missing confirm_success_url` error.

**Comment by MaicolBen** [comment]
Please don't use 0.2.0 unless you need #1159, use the latest. I guess it still happens in 1.0.0rc1, it's weird because we don't any call like `User.confirm_success_url` or `user.confirm_success_url`, can you post the backtrace when you set the variable (the other case is expected and you should set it)?

**Comment by lordkiz** [comment]
@MaicolBen Was experiencing this after my app on heroku autoupgraded the gem to 0.2.0. Had to revert to get it working again normally.
I will try to reproduce it on development and post a backtrace.

**Comment by geoffw8** [comment]
This is happening for me on 1.0.0 too.

**Comment by MaicolBen** [comment]
@geoffw8 can you post a backtrace?

**Comment by mrkrlli** [comment]
I'm seeing this error after adding `:confirmable` to the User model. Using version 1.1.0

```
ActiveModel::UnknownAttributeError at /auth
===========================================

> unknown attribute 'confirm_success_url' for User.

activemodel (5.2.2.1) lib/active_model/attribute_assignment.rb, line 53
-----------------------------------------------------------------------


   48         def _assign_attribute(k, v)
   49           setter = :"#{k}="
   50           if respond_to?(setter)
   51             public_send(setter, v)
   52           else
>  53             raise UnknownAttributeError.new(self, k)
   54           end
   55         end
   56     end
   57   end


App backtrace
-------------



Full backtrace
--------------

 - activemodel (5.2.2.1) lib/active_model/attribute_assignment.rb:53:in `_assign_attribute'
 - activemodel (5.2.2.1) lib/active_model/attribute_assignment.rb:44:in `block in _assign_attributes'
 - activemodel (5.2.2.1) lib/active_model/attribute_assignment.rb:43:in `_assign_attributes'
 - activerecord (5.2.2.1) lib/active_record/attribute_assignment.rb:23:in `_assign_attributes'
 - activemodel (5.2.2.1) lib/active_model/attribute_assignment.rb:35:in `assign_attributes'
 - activerecord (5.2.2.1) lib/active_record/core.rb:314:in `initialize'
 - devise (4.6.1) lib/devise/models/database_authenticatable.rb:41:in `initialize'
 - devise (4.6.1) lib/devise/models/confirmable.rb:67:in `initialize'
 - activerecord (5.2.2.1) lib/active_record/inheritance.rb:66:in `new'
 - devise_token_auth (1.1.0) app/controllers/devise_token_auth/registrations_controller.rb:101:in `build_resource'
 - devise_token_auth (1.1.0) app/controllers/devise_token_auth/registrations_controller.rb:11:in `create'
 - actionpack (5.2.2.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
 - actionpack (5.2.2.1) lib/abstract_controller/base.rb:194:in `process_action'
 - actionpack (5.2.2.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
 - actionpack (5.2.2.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
 - activesupport (5.2.2.1) lib/active_support/callbacks.rb:132:in `run_callbacks'
 - actionpack (5.2.2.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
 - actionpack (5.2.2.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
 - actionpack (5.2.2.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
 - activesupport (5.2.2.1) lib/active_support/notifications.rb:168:in `block in instrument'
 - activesupport (5.2.2.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
 - activesupport (5.2.2.1) lib/active_support/notifications.rb:168:in `instrument'
 - actionpack (5.2.2.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
 - actionpack (5.2.2.1) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
 - activerecord (5.2.2.1) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
 - actionpack (5.2.2.1) lib/abstract_controller/base.rb:134:in `process'
 - actionpack (5.2.2.1) lib/action_controller/metal.rb:191:in `dispatch'
 - actionpack (5.2.2.1) lib/action_controller/metal.rb:252:in `dispatch'
 - actionpack (5.2.2.1) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
 - actionpack (5.2.2.1) lib/action_dispatch/routing/route_set.rb:34:in `serve'
 - actionpack (5.2.2.1) lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>'
 - actionpack (5.2.2.1) lib/action_dispatch/routing/mapper.rb:48:in `serve'
 - actionpack (5.2.2.1) lib/action_dispatch/journey/router.rb:52:in `block in serve'
 - actionpack (5.2.2.1) lib/action_dispatch/journey/router.rb:35:in `serve'
 - actionpack (5.2.2.1) lib/action_dispatch/routing/route_set.rb:840:in `call'
 - warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
 - warden (1.2.8) lib/warden/manager.rb:34:in `call'
 - rack (2.0.6) lib/rack/tempfile_reaper.rb:15:in `call'
 - rack (2.0.6) lib/rack/etag.rb:25:in `call'
 - rack (2.0.6) lib/rack/conditional_get.rb:38:in `call'
 - rack (2.0.6) lib/rack/head.rb:12:in `call'
 - actionpack (5.2.2.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
 - rack (2.0.6) lib/rack/session/abstract/id.rb:232:in `context'
 - rack (2.0.6) lib/rack/session/abstract/id.rb:226:in `call'
 - actionpack (5.2.2.1) lib/action_dispatch/middleware/cookies.rb:670:in `call'
 - activerecord (5.2.2.1) lib/active_record/migration.rb:559:in `call'
 - actionpack (5.2.2.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
 - activesupport (5.2.2.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
 - actionpack (5.2.2.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
 - actionpack (5.2.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
 - better_errors (2.5.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
 - better_errors (2.5.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
 - better_errors (2.5.1) lib/better_errors/middleware.rb:57:in `call'
 - actionpack (5.2.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
 - actionpack (5.2.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
 - railties (5.2.2.1) lib/rails/rack/logger.rb:38:in `call_app'
 - railties (5.2.2.1) lib/rails/rack/logger.rb:26:in `block in call'
 - activesupport (5.2.2.1) lib/active_support/tagged_logging.rb:71:in `block in tagged'
 - activesupport (5.2.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'
 - activesupport (5.2.2.1) lib/active_support/tagged_logging.rb:71:in `tagged'
 - railties (5.2.2.1) lib/rails/rack/logger.rb:26:in `call'
 - sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
 - actionpack (5.2.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
 - actionpack (5.2.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
 - rack (2.0.6) lib/rack/method_override.rb:22:in `call'
 - rack (2.0.6) lib/rack/runtime.rb:22:in `call'
 - activesupport (5.2.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
 - actionpack (5.2.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
 - actionpack (5.2.2.1) lib/action_dispatch/middleware/static.rb:127:in `call'
 - rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
 - railties (5.2.2.1) lib/rails/engine.rb:524:in `call'
 - puma (3.12.1) lib/puma/configuration.rb:227:in `call'
 - puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
 - puma (3.12.1) lib/puma/server.rb:474:in `process_client'
 - puma (3.12.1) lib/puma/server.rb:334:in `block in run'
 - puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'

```

**Comment by zernie** [comment]
Same. Any idea why this could be happening?

**Comment by zernie** [comment]
Downgrading to `0.1.43` fixes the problem temporarily.

**Comment by alexmreis** [comment]
Still happens on 1.1.3

**Comment by dmc2015** [comment]
I had basic devise setup previously and never needed to provide a `confirm_success_url`.

I manually created the devise_auth_token controller for registration in my app. I changed my request because the error message says it needs the `confirm_success_url`, so I add it, updated `sign_up_params`.

If I don't update `sign_up_params` to this

```
  def sign_up_params
    params.permit(*params_for_resource(:sign_up), :confirm_success_url, :registration)
  end
```

It will say `confirm_success_url` isn't permitted.

Then later on after I do this it gets to the point where it can create the user and it says

`(unknown attribute 'confirm_success_url' for User.)`

The error messages seem circular and there is no clear way resolution.

UPDATE:
@lordkiz 
This worked, its from the link in the original post:
`config.default_confirm_success_url = "confirmed"`

I still get this message
`Unpermitted parameter: :registration` but it doesn't stop me from signing up. This seems like a conflict between devise_token_auth and default rails behavior. https://github.com/heartcombo/devise/issues/4825

**Comment by maysam** [comment]
do you have `include DeviseTokenAuth::Concerns::User` inserted in your user model?
