### ISSUE TITLE
PUT based routes not working

### ISSUE THREAD

**Issue by sofianegargouri** [lynndylanhurley/devise_token_auth#1215]
Hi,

I upgraded my app to Rails 5.2 and had to upgrade `devise_token_auth (0.1.42)` to the latest version. When doing so, all of my unit tests are passing, except the profile and password update. I can't really find what's wrong.

* **Version**: which version of this gem are you using?

```
* devise_token_auth (0.2.0)
        Summary: Token based authentication for rails. Uses Devise + OmniAuth.
        Homepage: http://github.com/lynndylanhurley/devise_token_auth
        Path: /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/devise_token_auth-0.2.0
```

* **Unit test**: these can be found in the "Network" tab of your browser's web inspector.

```
# frozen_string_literal: true

require 'acceptance_helper'

resource 'Authentication' do
  header 'Accept', 'application/json'
  header 'Content-Type', 'application/json'

  let(:user) { create(:user, confirmed_at: Time.zone.now) }
  let(:auth_token) { user.create_new_auth_token }
  let(:access_token) { auth_token['access-token'] }
  let(:token_type) { auth_token['token-type'] }
  let(:client_id) { auth_token['client'] }
  let(:expiry) { auth_token['expiry'] }
  let(:uid) { auth_token['uid'] }

  route '/auth', 'Authentication' do

    put 'Update current user' do
      header 'Access-Token', :access_token
      header 'Token-Type', :token_type
      header 'Client', :client_id
      header 'Expiry', :expiry
      header 'Uid', :uid

      parameter :firstname, "User's firstname"
      parameter :lastname, "User's lastname"
      parameter :locale, "User's locale"

      let(:user) { build(:user) }
      let(:firstname) { user.firstname }
      let(:lastname) { user.lastname }
      let(:locale) { user.locale }

      example_request 'Update current user' do
        expect(response_status).to eq(200)
        response = JSON.parse(response_body)
        expect(response['data']['firstname']).to eq(firstname)
      end
    end
  end

  route 'auth/password', 'User password' do
    post 'Request password reset email' do
      parameter :email, "User's email", required: true
      parameter :redirect_url, 'URL to redirect to on email opening', required: true

      let(:email) { user.email }
      let(:redirect_url) { Faker::Internet.url }
    end

    put "Update current user's password" do
      header 'Access-Token', :access_token
      header 'Token-Type', :token_type
      header 'Client', :client_id
      header 'Expiry', :expiry
      header 'Uid', :uid

      parameter :password, "User's new password", required: true
      parameter :password_confirmation, "User's new password confirmation", required: true

      let(:user) { build(:user) }
      let(:password) { user.password }
      let(:password_confirmation) { user.password }

      example_request "Update current user's password" do
        expect(response_status).to eq(200)
      end
    end
  end
end
```

Output:

```
Authentication
  /auth Authentication
    PUT Update current user
      Update current user (FAILED - 1)
  auth/password User password
    PUT Update current user's password
      Update current user's password (FAILED - 2)

Failures:

  1) Authentication /auth Authentication PUT Update current user Update current user
     Failure/Error: expect(response_status).to eq(200)

       expected: 200
            got: 404

       (compared using ==)
     # ./spec/acceptance/auth_spec.rb:36:in `block (4 levels) in <top (required)>'

  2) Authentication auth/password User password PUT Update current user's password Update current user's password
     Failure/Error: expect(response_status).to eq(200)

       expected: 200
            got: 401

       (compared using ==)
     # ./spec/acceptance/auth_spec.rb:67:in `block (4 levels) in <top (required)>'

Finished in 2.67 seconds (files took 3.65 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./spec/acceptance/auth_spec.rb:35 # Authentication /auth Authentication PUT Update current user Update current user
rspec ./spec/acceptance/auth_spec.rb:66 # Authentication auth/password User password PUT Update current user's password Update current user's password
```

* **Environmental Info**: How is your application different from the [reference implementation](https://github.com/lynndylanhurley/devise_token_auth_demo)? This may include (but is not limited to) the following details:
  * **Routes**: are you using some crazy namespace, scope, or constraint? **No**
  * **Gems**: are you using MongoDB, Grape, RailsApi, ActiveAdmin, etc.? **No**
  * **Custom Overrides**: what have you done in terms of [custom controller overrides](https://github.com/lynndylanhurley/devise_token_auth/#custom-controller-overrides)? **Nothing**
  * **Custom Frontend**: are you using [ng-token-auth](https://github.com/lynndylanhurley/ng-token-auth), [jToker](https://github.com/lynndylanhurley/j-toker), [Angular2-Token](https://github.com/neroniaky/angular2-token), or something else? **No frontend here**

**Comment by MaicolBen** [comment]
0.2.0 isn't the lastest version, it's 1.0.0rc1, I will release the second release candidate and 1.0.0 will come soon, can you check with 1.0.0rc1 or master?

**Comment by sofianegargouri** [comment]
Same error with

```
  * devise_token_auth (1.0.0.rc1 8bad4e2)
        Summary: Token based authentication for rails. Uses Devise + OmniAuth.
        Homepage: http://github.com/lynndylanhurley/devise_token_auth
        Path: /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/bundler/gems/devise_token_auth-8bad4e2a5fb7
```

**Comment by MaicolBen** [comment]
Thanks, the user isn't found, the problem is in `set_user_by_token` method, do you have `enable_standard_devise_support` in true?

I don't see a way to find the problem without debugging, you can override that method in the controller (passwords or registrations controller):
```ruby
def set_user_by_token
  binding.pry # or byebug
  super
end
```

**Comment by MaicolBen** [comment]
@sofianegargouri did you have luck?

**Comment by sofianegargouri** [comment]
Nop, unfortunately :(
