### ISSUE TITLE
Unable to create user with mongodb as ORM

### ISSUE THREAD

**Issue by opsydev** [lynndylanhurley/devise_token_auth#1293]
Using mongo the save for a user model fails with `NoMethodError (undefined method `saved_change_to_encrypted_password?' for #<User:0x00007f81d8608ba8>):`

This is on a brand new Rails 6.0.0 set up. I had to do a `bundle exec rails g devise:install` along with `bundle exec rails g devise_token_auth:install_mongoid User auth`.

Using postman to make a post request to /auth with the following params gives the attached stacktrace. 
```
{
  	"email": "Charity_Leffler@gmail.com",
  	"password": "password123",
  	"password_confirmation": "password123",
  	"name": "Kristy Skiles"
}
```

Looks like Mongoid doesn't support the new ActiveRecord API yet (https://jira.mongodb.org/browse/MONGOID-4528)

* **Version**: 
    - devise_token_auth (1.1.0). 
    - Ruby 2.5.5 Rails 
    - Rails 6.0.0-rc1

* **Rails Stacktrace**: this can be found in the `log/development.log` of your API.
```
   
NoMethodError (undefined method `saved_change_to_encrypted_password?' for #<User:0x00007f81d8608ba8>):
  
devise_token_auth (1.1.0) app/models/devise_token_auth/concerns/user.rb:230:in `should_remove_tokens_after_password_reset?'
devise_token_auth (1.1.0) app/models/devise_token_auth/concerns/user.rb:236:in `remove_tokens_after_password_reset'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:429:in `block in make_lambda'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:201:in `block (2 levels) in halting'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:607:in `block (2 levels) in default_terminator'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:606:in `catch'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:606:in `block in default_terminator'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:202:in `block in halting'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:514:in `block in invoke_before'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:514:in `each'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:514:in `invoke_before'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:134:in `run_callbacks'
mongoid (7.0.3) lib/mongoid/interceptable.rb:132:in `run_callbacks'
mongoid (7.0.3) lib/mongoid/persistable/creatable.rb:118:in `prepare_insert'
mongoid (7.0.3) lib/mongoid/persistable/creatable.rb:23:in `insert'
mongoid (7.0.3) lib/mongoid/persistable/savable.rb:23:in `save'
devise_token_auth (1.1.0) app/controllers/devise_token_auth/registrations_controller.rb:42:in `create'
actionpack (6.0.0.rc1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.0.rc1) lib/abstract_controller/base.rb:196:in `process_action'
actionpack (6.0.0.rc1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.0.0.rc1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:135:in `run_callbacks'
actionpack (6.0.0.rc1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.0.rc1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.0.rc1) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.0.rc1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.0.rc1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.0.rc1) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
mongoid (7.0.3) lib/mongoid/railties/controller_runtime.rb:19:in `process_action'
actionpack (6.0.0.rc1) lib/abstract_controller/base.rb:136:in `process'
actionpack (6.0.0.rc1) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (6.0.0.rc1) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (6.0.0.rc1) lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
actionpack (6.0.0.rc1) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.0.rc1) lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>'
actionpack (6.0.0.rc1) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (6.0.0.rc1) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.0.rc1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.0.rc1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.0.rc1) lib/action_dispatch/routing/route_set.rb:837:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/etag.rb:25:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/conditional_get.rb:38:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/head.rb:12:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
railties (6.0.0.rc1) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.0.rc1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.0.rc1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.0.rc1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.0.rc1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
activesupport (6.0.0.rc1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/static.rb:126:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
railties (6.0.0.rc1) lib/rails/engine.rb:526:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

* **Environmental Info**: Created a brand new application with just the user model.

**Comment by opsydev** [comment]
So on a bit of further investigation, a quick fix for this would be changing [this line](https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/models/devise_token_auth/concerns/user.rb#L217) to be `if Rails::VERSION::MAJOR <= 5 || !respond_to?('saved_change_to_encrypted_password?')`

Not sure if this is an acceptable change. If it is I can create a MR for it. Until this is sorted I have just overridden the method in my `app/user.rb` with the change.

**Comment by MaicolBen** [comment]
Check #1328 way, it should be a cleaner way to ask that
