### ISSUE TITLE
Generate authorization headers without the need for an email and password.

### ISSUE THREAD

**Issue by dcastrososa** [lynndylanhurley/devise_token_auth#1298]
Is there any way to generate authorization headers without the need to provide email and password ?. This previously worked for me, I do not know what happened, I'm not sure if it has something to do with the version.

I just need to know if I can generate authorization tokens without email and password.

I have a login with google in my front end application. My approach is that this function receives the Google tokenId, verify that it is valid and then create a new user or search for an existing one in the database and respond with the authorization headers. In the case of not existing a user, the headers are created successfully, nevertheless when it tries to generate headers of authorization to an existing user I obtain the error of below.

```ruby
def self.validate_login_google token
    user = nil
    headers = nil
    response = HTTParty.get("https://www.googleapis.com/oauth2/v3/tokeninfo?id_token=#{token}", format: :json)

    if response.code == 200 
      body = JSON.parse response.body
      user = User.find_by(email: body["email"])
      if !user
        user = User.create(
          email: body["email"], name: body["name"].to_s.split(' ')[0], 
          last_name: body["name"].to_s.split(' ')[1],
          uid: body["email"], provider: "email", sign_in_count: 0, token: User.generate_token, password: User.generate_token, avatar: "", confirmated: true).save
        user = User.find_by(email: body["email"]).as_json(include: [:picture_users, :picture_covers, :publication_owners])
      end
     headers = user.create_new_auth_token
    end

    response = Hash.new 
    response["user"] = user 
    response["headers"] = headers
    response
end
```

```
# frozen_string_literal: true

DeviseTokenAuth.setup do |config|
  config.change_headers_on_each_request = false
  # By default the authorization headers will change after each request. The
  # client is responsible for keeping track of the changing tokens. Change
  # this to false to prevent the Authorization header from changing after
  # each request.
  # config.change_headers_on_each_request = true

  # By default, users will need to re-authenticate after 2 weeks. This setting
  # determines how long tokens will remain valid after they are issued.
  # config.token_lifespan = 2.weeks

  # Sets the max number of concurrent devices per user, which is 10 by default.
  # After this limit is reached, the oldest tokens will be removed.
  # config.max_number_of_devices = 10

  # Sometimes it's necessary to make several requests to the API at the same
  # time. In this case, each request in the batch will need to share the same
  # auth token. This setting determines how far apart the requests can be while
  # still using the same auth token.
  # config.batch_request_buffer_throttle = 5.seconds

  # This route will be the prefix for all oauth2 redirect callbacks. For
  # example, using the default '/omniauth', the github oauth2 provider will
  # redirect successful authentications to '/omniauth/github/callback'
  # config.omniauth_prefix = "/omniauth"

  # By default sending current password is not needed for the password update.
  # Uncomment to enforce current_password param to be checked before all
  # attribute updates. Set it to :password if you want it to be checked only if
  # password is updated.
  # config.check_current_password_before_update = :attributes

  # By default we will use callbacks for single omniauth.
  # It depends on fields like email, provider and uid.
  # config.default_callbacks = true

  # Makes it possible to change the headers names
  # config.headers_names = {:'access-token' => 'access-token',
  #                        :'client' => 'client',
  #                        :'expiry' => 'expiry',
  #                        :'uid' => 'uid',
  #                        :'token-type' => 'token-type' }

  # By default, only Bearer Token authentication is implemented out of the box.
  # If, however, you wish to integrate with legacy Devise authentication, you can
  # do so by enabling this flag. NOTE: This feature is highly experimental!
  # config.enable_standard_devise_support = false
end

```
Request
```javascript
const authWithGoogle = tokenId => {
  return dispatch => {
    dispatch(authStart())
    const dataLogin = {token: tokenId}

    axios.post(`${ip}/validate_login_google`, dataLogin)
      .then((data) => {
        setHeader(data.headers)
        dispatch(authSuccess(data.data, true))
        dispatch(setWelcomeMessage(true))
        dispatch(getFollows(data.data.id))
        dispatch(getUsersFollow(data.data.id))
        dispatch(getShares(data.data.id))
        dispatch(getLikes(data.data.id))
        dispatch(getAllData(data.data.token))
        localStorage.setItem('tokenId', data.data.token)
        localStorage.setItem('userId', data.data.id)
      }).catch((error) => {
        dispatch(authFail('Lo sentimos, hubo un error'))
      })
  }
}
```

This is the error.
```
{status: 422, error: "Unprocessable Entity",…}
error
:
"Unprocessable Entity"
exception
:
"#<ActiveRecord::RecordInvalid: Validation failed: Clave es requerido>"
status
:
422
traces
:
{Application Trace: [{id: 14, trace: "app/controllers/users_controller.rb:68:in `index'"}],…}
Application Trace
:
[{id: 14, trace: "app/controllers/users_controller.rb:68:in `index'"}]
Framework Trace
:
[,…]
Full Trace
:
[,…]
```

**Comment by MaicolBen** [comment]
@dcastrososa So in users#index, you are sending the headers that you set from `validate_login_google`, but that controller isn't detecting the user, I guess you have `before_action :authenticate_user!` in that controller. Can you post what you have in `app/controllers/users_controller.rb:68` ?
