### ISSUE TITLE
rake db:migrate complains of multiple databases and an old OmniAuth version

### ISSUE THREAD

**Issue by mgmodell** [lynndylanhurley/devise_token_auth#1456]
I am trying to run the tests on a clean pull of HEAD as of 1/17/2021 (c922580), but the bundle install takes hours and once it completes, it complains of a multiple database configuration and an old OmniAuth version (but it's using 2.0.1). If this is not an issue, please tell me what I'm doing wrong.

* **Version**: Head (as of 1/17)
* **Request and response headers**: n/a
* **Stacktrace**:
$ bundle exec rake db:migrate
Rails couldn't infer whether you are using multiple databases from your database.yml and can't generate the tasks for the non-primary databases. If you'd like to use this feature, please simplify your ERB.
rake aborted!
You are using an old OmniAuth version, please ensure you have 1.0.0.pr2 version or later installed.
/home/micah/dev/devise_token_auth/test/dummy/app/active_record/unregisterable_user.rb:5:in `<class:UnregisterableUser>'
/home/micah/dev/devise_token_auth/test/dummy/app/active_record/unregisterable_user.rb:4:in `<top (required)>'
/home/micah/dev/devise_token_auth/lib/devise_token_auth/rails/routes.rb:35:in `mount_devise_token_auth_for'
/home/micah/dev/devise_token_auth/test/dummy/config/routes.rb:17:in `block in <top (required)>'
/home/micah/dev/devise_token_auth/test/dummy/config/routes.rb:3:in `<top (required)>'
/home/micah/dev/devise_token_auth/test/dummy/config/environment.rb:7:in `<top (required)>'
/home/micah/.asdf/installs/ruby/2.7.2/bin/bundle:23:in `load'
/home/micah/.asdf/installs/ruby/2.7.2/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate => app:db:migrate => app:db:load_config => app:environment
(See full trace by running task with --trace)

* **Environmental Info**: asdf version manager with ruby 2.7.2

**Comment by gamesover** [comment]
it seems can only support omniauth version < 2 for now
