### ISSUE TITLE
Error on OmniauthCallbacksController#omniauth_success

### ISSUE THREAD

**Issue by samuelmartinucci2** [lynndylanhurley/devise_token_auth#222]
I am facing the following problem and would be thankful if anyone could help me:

**Logs:**

```
Processing by DeviseTokenAuth::OmniauthCallbacksController#omniauth_success as HTML
  Parameters: {"auth_origin_url"=>"http://localhost:9000/#/sign_in", "oauth_token"=>"IyN9tmUV60TI9lrkafiJzTDc3QlmO8n5", "oauth_verifier"=>"VyOdonlmCMLF08zeJvseVw0kdyV4s59U", "provider"=>"twitter"}
Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.0ms)

NoMethodError (undefined method `constantize' for nil:NilClass):
  devise_token_auth (0.1.31) app/controllers/devise_token_auth/omniauth_callbacks_controller.rb:110:in `resource_class'
  devise_token_auth (0.1.31) app/controllers/devise_token_auth/omniauth_callbacks_controller.rb:23:in `omniauth_success'
  actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/mapper.rb:49:in `serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:404:in `call_app!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:362:in `callback_phase'
  omniauth-oauth (1.1.0) lib/omniauth/strategies/oauth.rb:57:in `callback_phase'
  omniauth (1.2.2) lib/omniauth/strategy.rb:227:in `callback_call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:184:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.2.2) lib/omniauth/builder.rb:59:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.0) lib/rack/etag.rb:24:in `call'
  rack (1.6.0) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.0) lib/rack/head.rb:13:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
  activerecord (4.2.1) lib/active_record/migration.rb:378:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
```

**routes.rb**

```
Rails.application.routes.draw do
  scope :api do
    mount_devise_token_auth_for 'User', at: 'auth'

    get '/time_records/current' => "time_records#current"
    resources :time_records, except: [:new, :edit]
  end
end
```

**gems**

```
gem 'devise_token_auth'
gem 'omniauth-twitter'
gem 'omniauth-linkedin'
gem 'omniauth-facebook'
gem 'omniauth-google-oauth2'

gem 'figaro'

gem 'activerecord-session_store'
```

**application_controller.rb:**

``` ruby
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  include DeviseTokenAuth::Concerns::SetUserByToken
  include ActionController::MimeResponds

  def self.respond_to(*mimes)
    include ActionController::RespondWith::ClassMethods
  end

  respond_to :json

end
```

Everything is working fine except omniauth authentication (with any provider).

**Comment by samuelmartinucci2** [comment]
Now it gave me a different error:

```
NoMethodError (undefined method `[]' for nil:NilClass):
  devise_token_auth (0.1.31) app/controllers/devise_token_auth/omniauth_callbacks_controller.rb:24:in `omniauth_success'
  actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
```

**Comment by samuelmartinucci2** [comment]
Without changing anything, the error has changed again, now seems that Twitter started sending uid (they were not), but the error has changed again...

ctionView::MissingTemplate (Missing template devise_token_auth/omniauth_callbacks/omniauth_success, devise_token_auth/application/omniauth_success, devise/omniauth_success, application/omniauth_success with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder]}. Searched in:
  * "/home/samuel/projetos/ruby/time-report/app/views"
  * "/var/lib/gems/2.1.0/gems/devise_token_auth-0.1.31/app/views"
  * "/var/lib/gems/2.1.0/gems/devise-3.4.1/app/views"
):
  actionview (4.2.1) lib/action_view/path_set.rb:46:in `find'
  actionview (4.2.1) lib/action_view/lookup_context.rb:121:in `find'
  actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:18:in `find_template'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:40:in `determine_template'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:8:in `render'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.1) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.1) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.1) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.1) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:16:in `render'

**Comment by jancel** [comment]
Did you ever work through this? I'm having the same issue right now.

**Comment by zachfeldman** [comment]
Hi there @samuelmartinucci2    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
