### ISSUE TITLE
Warden::SessionSerializer - wrong number of arguments (2 for 1)

### ISSUE THREAD

**Issue by BjornMelgaard** [lynndylanhurley/devise_token_auth#312]
Error appears because I have two root paths
```ruby
  authenticated :user do
    root 'application#index', as: :authenticated_root
  end

  root to: redirect('/auth/login'), as: :unauthenticated_root
```

When I remove path as `authenticated_root` error go away ( not `unauthenticated_root`, in this case error persist ) 

> ### PS
> [Application path](https://github.com/BjornMelgaard/todoapp)
> `devise_token_auth` version `0.1.32.beta10 07ca81c` (fetched from git)
> When I installed `devise_token_auth`, I din't initialize `devise`, only `devise_token_auth`
> also `config.change_headers_on_each_request = false`

**Comment by BjornMelgaard** [comment]
I change `routers.rb` to 
```ruby
  root 'application#index'

  get "auth/login", to: "application#login" , as: "login"
  get "auth/facebook", to: "application#login", as: "facebook"
  get "auth/registration", to: "application#login", as: "registration"
```
and  I found that `user_signed_in?` raise that error too

Error stack:
```bash
ArgumentError - wrong number of arguments (2 for 1):
  devise (3.5.1) lib/devise.rb:457:in `block (2 levels) in configure_warden!'
  warden (1.2.3) lib/warden/session_serializer.rb:34:in `fetch'
  warden (1.2.3) lib/warden/proxy.rb:212:in `user'
  /home/bjorn/.bundler/ruby/2.2.0/devise_token_auth-07ca81c1d352/app/controllers/devise_token_auth/concerns/set_user_by_token.rb:32:in `set_user_by_token'
  /home/bjorn/.bundler/ruby/2.2.0/devise_token_auth-07ca81c1d352/lib/devise_token_auth/controllers/helpers.rb:115:in `current_user'
  /home/bjorn/.bundler/ruby/2.2.0/devise_token_auth-07ca81c1d352/lib/devise_token_auth/controllers/helpers.rb:111:in `user_signed_in?'
  actionpack (4.2.3) lib/abstract_controller/helpers.rb:67:in `user_signed_in?'
  app/views/layouts/_debug.slim:4:in `_app_views_layouts__debug_slim___2147060343315952264_69908902597980'
  actionview (4.2.3) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.3) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.3) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.3) lib/action_view/template.rb:143:in `render'
  actionview (4.2.3) lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
  actionview (4.2.3) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
  actionview (4.2.3) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.3) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.3) lib/action_view/renderer/partial_renderer.rb:309:in `render'
  actionview (4.2.3) lib/action_view/renderer/renderer.rb:47:in `render_partial'
  actionview (4.2.3) lib/action_view/helpers/rendering_helper.rb:35:in `render'
  app/views/layouts/application.html.slim:15:in `_app_views_layouts_application_html_slim__1088578683254279594_69908896638320'
  actionview (4.2.3) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.3) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.3) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.3) lib/action_view/template.rb:143:in `render'
  actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
  actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.3) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.3) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.3) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.3) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.3) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.3) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.3) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.3) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.3) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.3) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /usr/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
  activesupport (4.2.3) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.3) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:43:in `render'
  actionpack (4.2.3) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (4.2.3) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  actionpack (4.2.3) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.3) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.3) lib/active_support/callbacks.rb:115:in `call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
  activesupport (4.2.3) lib/active_support/callbacks.rb:503:in `call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:88:in `run_callbacks'
  actionpack (4.2.3) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.3) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.3) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.3) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.3) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.3) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.3) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:45:in `serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:821:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.2.2) lib/omniauth/builder.rb:59:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.3) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.3) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:84:in `run_callbacks'
  actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.2.1) lib/web_console/middleware.rb:39:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.3) lib/rails/engine.rb:518:in `call'
  railties (4.2.3) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /usr/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /usr/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /usr/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

**Comment by BjornMelgaard** [comment]
Handle with this by downgrading Rails from 2.2.3 to 2.2.2

But there was another error
