### ISSUE TITLE
Defining a custom primary key

### ISSUE THREAD

**Issue by mustela** [lynndylanhurley/devise_token_auth#378]
Maybe is a dummy question, sorry for that, but I'm starting with the rails/devise world. 

I  have a rails website running with the gem configured, some details: 
```
* Rails 4.2.4
* ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin14.0]
* devise_token_auth (0.1.34)
* devise (= 3.5.1)
```

I've run the generator so I have a migration file with 

```
def change
    create_table :users, id: :uuid do |t|

      ## Required
      t.string :provider, null: false, default: "email"
      t.string :uid, :null => false, :default => ""
      t.string :email, null: false

      ## Database authenticatable
      t.string :encrypted_password, null: false, default: ""

      ## Recoverable
      t.string   :reset_password_token
      t.datetime :reset_password_sent_at

      ## Rememberable
      t.datetime :remember_created_at

      ## Trackable
      t.integer  :sign_in_count, default: 0, null: false
      t.datetime :current_sign_in_at
      t.datetime :last_sign_in_at
      t.string   :current_sign_in_ip
      t.string   :last_sign_in_ip

      ## Confirmable
      t.string   :confirmation_token
      t.datetime :confirmed_at
      t.datetime :confirmation_sent_at
      t.string   :unconfirmed_email # Only if using reconfirmable

      ## Lockable
      t.integer  :failed_attempts, default: 5, null: false # Only if lock strategy is :failed_attempts
      t.string   :unlock_token # Only if unlock strategy is :email or :both
      t.datetime :locked_at

      ## User Info
      t.string :nickname
      t.string :image_url
      t.string :first_name, :last_name, null: false
      t.string :otp_secret_key, null: false
      t.json :recovery_codes, null: false, default: {}
      t.json :fraud_details
      t.string :two_factor_auth, null: true, default: nil
      t.hstore :settings, null: false, default: { timezone: 'America/New_York' }
      t.hstore :social, null: false, default: {}
      t.uuid :last_login_from

      ## Tokens
      t.json :tokens

      t.timestamps
      t.soft_deletable
    end

    add_index :users, [:uid, :provider],     :unique => true
    add_index :users, :reset_password_token, :unique => true
    add_index :users, :email, :unique => true

```

And as you can see I've defined a primary key `id: :uuid`, because all my models have that structure. And now I'm having some issues with that. For instance when I try to sign up a user, it is raising: 

```
Couldn't find User with 'id'=testing@example.com (ActiveRecord::RecordNotFound)
      /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.4/lib/active_record/relation/finder_methods.rb:324:in `raise_record_not_found_exception!'
      /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.4/lib/active_record/relation/finder_methods.rb:444:in `find_one'
      /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.4/lib/active_record/relation/finder_methods.rb:423:in `find_with_ids'
      /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.4/lib/active_record/relation/finder_methods.rb:71:in `find'
      /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.4/lib/active_record/persistence.rb:414:in `block in reload'
      /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.4/lib/active_record/scoping/default.rb:33:in `block in unscoped'
      /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.4/lib/active_record/relation.rb:302:in `scoping'
      /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.4/lib/active_record/scoping/default.rb:33:in `unscoped'
      /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.4/lib/active_record/persistence.rb:414:in `reload'
      /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.4/lib/active_record/attribute_methods/dirty.rb:36:in `reload'
      /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.4/lib/active_record/autosave_association.rb:227:in `reload'
      /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.4/lib/active_record/locking/pessimistic.rb:62:in `lock!'
      /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.4/lib/active_record/locking/pessimistic.rb:71:in `block in with_lock'
      /usr/local/lib/ruby/gems/2.1.0/gems/test_after_commit-0.4.1/lib/test_after_commit.rb:15:in `block in transaction_with_transactional_fixtures'
      /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
      /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
      /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
      /usr/local/lib/ruby/gems/2.1.0/gems/test_after_commit-0.4.1/lib/test_after_commit.rb:9:in `transaction_with_transactional_fixtures'
      /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:220:in `transaction'
      /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:277:in `transaction'
      /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.4/lib/active_record/locking/pessimistic.rb:70:in `with_lock'
      /usr/local/Cellar/ruby/2.1.3/lib/ruby/gems/2.1.0/gems/devise_token_auth-0.1.34/app/controllers/devise_token_auth/concerns/set_user_by_token.rb:82:in `update_auth_header'
```

Because I believe is trying to use the uid as a primary key. 

So is there a way to specify which is the primary key and use that or am I missing something here? 

Thanks a lot!

**Comment by mustela** [comment]
Just forget about it, it was just an issue after changing things that I shouldn't.
