### ISSUE TITLE
redirect_uri_mismatch after update from 0.1.34 to 0.1.37 

### ISSUE THREAD

**Issue by h3xed** [lynndylanhurley/devise_token_auth#420]
After update from version 0.1.34 to 0.1.37 i have redirect_uri_mismatch error in google (facebook work fine). I didn't change any other data.

Google msg:
"The redirect URI in the request: https://xxx.com/api/omniauth/google_oauth2/callback?auth_origin_url=https%3A%2F%2Fxxx.com%2F%23%2Fsignin&amp;omniauth_window_type=sameWindow&amp;resource_class=User did not match a registered redirect URI."

Redirect URI in google console:
https://xxx.com/api/omniauth/google_oauth2/callback

Maybe it's problem with uri encode?

**Comment by booleanbetrayal** [comment]
Looks to be possibly a breaking change with omniauth-oauth2 in 1.4.0. -- https://github.com/intridea/omniauth-oauth2/pull/82

Could you check your omniauth-oauth2 gem version? We may need to pin to a last known stable, etc.

**Comment by h3xed** [comment]
I had 1.4.0, when i rollback to 1.3.1, redirect URI looks good (for google) but i have runtime error on oauth provider callback: 

```
RuntimeError (No resource_class found):
  devise_token_auth (0.1.37.beta3) app/controllers/devise_token_auth/omniauth_callbacks_controller.rb:106:in `resource_class'
  devise_token_auth (0.1.37.beta3) app/controllers/devise_token_auth/omniauth_callbacks_controller.rb:233:in `get_resource_from_auth_hash'
  devise_token_auth (0.1.37.beta3) app/controllers/devise_token_auth/omniauth_callbacks_controller.rb:26:in `omniauth_success'
[...]
```

**Comment by michaelamato** [comment]
Where are 1.4.0 version? I see only 1.3.7beta3

**Comment by h3xed** [comment]
1.4.0 version of omniauth-oauth2 gem.

**Comment by dtelaroli** [comment]
+1 
downgrade to omniauth-oauth2 1.3.1 works

**Comment by zachfeldman** [comment]
Sounds like we have a solution to this problem and no activity in almost 2 years. Closing for now.
