### ISSUE TITLE
Undefined method provider from devise_toke_auth concerns/user.rb

### ISSUE THREAD

**Issue by arinhouck** [lynndylanhurley/devise_token_auth#438]
RUBY 2.2.2
    devise (3.5.2)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    devise_token_auth (0.1.30)
      devise (~> 3.3)
      rails (~> 4.1)

```
NoMethodError: undefined method `provider' for #<Admin:0x007fa2ede615a8>
/Users/arinhouck/.rvm/gems/ruby-2.2.2/gems/activemodel-4.1.8/lib/active_model/attribute_methods.rb:435:in `method_missing'
/Users/arinhouck/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.8/lib/active_record/attribute_methods.rb:213:in `method_missing'
/Users/arinhouck/.rvm/gems/ruby-2.2.2/gems/devise_token_auth-0.1.30/app/models/devise_token_auth/concerns/user.rb:13:in `block (2 levels) in <module:User>'
/Users/arinhouck/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:440:in `instance_exec'
/Users/arinhouck/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:440:in `block in make_lambda'
/Users/arinhouck/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:175:in `call'
/Users/arinhouck/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:175:in `block (2 levels) in conditional'
/Users/arinhouck/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:175:in `each'
/Users/arinhouck/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:175:in `all?'
/Users/arinhouck/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:175:in `block in conditional'
```
Only provided top part of stack trace as it was most relevant. The line doesn't seem to be accurate but I assumed something along these lines:
https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/models/devise_token_auth/concerns/user.rb
```
    validates :email, presence: true, email: true, if: Proc.new { |u| u.provider == 'email' }
    validates_presence_of :uid, if: Proc.new { |u| u.provider != 'email' }

  def unique_email_user
    if provider == 'email' and self.class.where(provider: 'email', email: email).count > 0
      errors.add(:email, :already_in_use)
    end
  end
```

My schema appears to not include provider as shown here:
https://github.com/lynndylanhurley/devise_token_auth/blob/1084ec2f2d87548c34840dbc4afd804660764f18/test/dummy/db/schema.rb

**Comment by arinhouck** [comment]
Well, after a bit of confusion. I figured it out. I was missing important migration information, not sure what could have caused this. Potentially changing ruby versions and a new bundle set. Anyways, here was my migration:

```
class AddProviderToUser < ActiveRecord::Migration
  def change
    add_column :users, :provider, :string, :null => false, :default => "email"
    add_column :users, :uid, :string, :null => false

    add_index :users, [:uid, :provider], unique: true
  end
end
```
