### ISSUE TITLE
cancancan: load_and_authorize_resources causes method_missing failure

### ISSUE THREAD

**Issue by lolgear** [lynndylanhurley/devise_token_auth#452]
setup:

```
cancancan-1.13.1
rails-4.2.5
devise_token_auth - commit #df960d9409dcd4476a3f6694e8bf30e57000599a

```

```
class DevicesController < ApiBaseController
    before_filter :output_user
  # load_and_authorize_resource
  inherit_resources
  respond_to :json

  def output_user
    puts "current user is: #{@current_user}"
  end

  def index     
    @devices = Device.all.sorted_by(params[:sort])
    render json: @devices, status: :ok
  end
end
```

works fine, but when I try to uncomment `load_and_authorize_resources`, I got error:

```
NoMethodError (undefined method `find_by_uid' for #<Class:0x007f8499a78670>):
  activerecord (4.2.5) lib/active_record/dynamic_matchers.rb:26:in `method_missing'
  devise_token_auth/app/controllers/devise_token_auth/concerns/set_user_by_token.rb:71:in `set_user_by_token'
  devise_token_auth/lib/devise_token_auth/controllers/helpers.rb:116:in `current_user'
  cancancan (1.13.1) lib/cancan/controller_additions.rb:357:in `current_ability'
  cancancan (1.13.1) lib/cancan/controller_resource.rb:214:in `current_ability'
  cancancan (1.13.1) lib/cancan/controller_resource.rb:72:in `load_collection?'
  cancancan (1.13.1) lib/cancan/controller_resource.rb:33:in `load_resource'
  cancancan (1.13.1) lib/cancan/controller_resource.rb:25:in `load_and_authorize_resource'
  cancancan (1.13.1) lib/cancan/controller_resource.rb:10:in `block in add_before_filter'
```

I try to fix resource_class collision bug by:

```
    def set_user_by_token(mapping=nil)
    # ......
    rc = resource_class(mapping) rescue resource_class

    # .......

    puts "this class is: #{rc}"
    user = uid && rc.find_by_uid(uid)
```

But when I try to access to /devices.json, I see:

```
this class is: Device
Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.7ms)

NoMethodError (undefined method `find_by_uid' for #<Class:0x007f849b67d578>):
```

**Comment by lolgear** [comment]
#454

**Comment by zachfeldman** [comment]
Hi there @lolgear    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
