### ISSUE TITLE
Unable to call `rails g devise_token_auth:install` within rails engine

### ISSUE THREAD

**Issue by djsegal** [lynndylanhurley/devise_token_auth#465]
getting this error when I run it within my api engine:

```
.../activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:878:in `retrieve_connection': No connection pool for ActiveRecord::Base (ActiveRecord::ConnectionNotEstablished)
  from .../activerecord/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
  from .../activerecord/lib/active_record/connection_handling.rb:87:in `connection'
  from /devise_token_auth/lib/generators/devise_token_auth/install_generator.rb:154:in `database_name'
  from /devise_token_auth/lib/generators/devise_token_auth/install_generator.rb:136:in `postgres?'
  from /devise_token_auth/lib/generators/devise_token_auth/install_generator.rb:132:in `json_supported_database?'
  from (erb):43:in `migration_template'
```

* i believe this is because the base directory doesn't have a `config/database.yml` file (because it is actually kept at `./spec/dummy/config/database.yml`). 
* i tried monkey around with it to get it to work, but I eventually gave up and just made `json_supported_database?` always return `true`

**Comment by shifakhan** [comment]
@djsegal Were you able to get devise_token_auth running in the engine ?

**Comment by Bengals10** [comment]
I have the same issue

**Comment by djsegal** [comment]
Have long since refactored my own code and genuinely have no clue what this is about
