### ISSUE TITLE
RuntimeError (can't modify frozen Hash)

### ISSUE THREAD

**Issue by hybmg57** [lynndylanhurley/devise_token_auth#515]
I'm getting below error from devise token auth which seems to happen occasionally.

```
I, [2016-01-27T23:05:39.111421 #894]  INFO -- : Completed 500 Internal Server Error in 13ms (Views: 2.2ms | ActiveRecord: 4.3ms)
F, [2016-01-27T23:05:39.112397 #894] FATAL -- :
RuntimeError (can't modify frozen Hash):
  /usr/local/rvm/gems/ruby-2.2.1/gems/devise_token_auth-0.1.36/app/controllers/devise_token_auth/concerns/set_user_by_token.rb:78:in `update_auth_header'
  /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'
  /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:239:in `call'
  /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:239:in `block in halting'
  /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:506:in `call'
  /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:506:in `block in call'
  /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:506:in `each'
  /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:506:in `call'
  /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'
  /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
  /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
  /usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.2.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
  /usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
  /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
  /usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  /usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.2.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:137:in `process'
  /usr/local/rvm/gems/ruby-2.2.1/gems/actionview-4.2.1/lib/action_view/rendering.rb:30:in `process'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rack-mini-profiler-0.9.8/lib/mini_profiler/profiling_methods.rb:77:in `block in profile_method'
  /usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.2.1/lib/action_controller/metal/live.rb:278:in `block in process'
```

Had a look at the code set_user_by_token.rb:78 and it's failing on below code

```
# update the response header
response.headers.merge!(auth_header)
```

**Comment by hybmg57** [comment]
Anyone?

**Comment by a7medfahmy94** [comment]
Same here, It started to show when I set this options
`config.change_headers_on_each_request = false`

![screenshot from 2016-08-17 13 21 08](https://cloud.githubusercontent.com/assets/6239724/17734594/7c120ebc-647d-11e6-8123-67f59739398f.png)

**Comment by zachfeldman** [comment]
Hi there @hybmg57 and @a7medfahmy94    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
