### ISSUE TITLE
NoMethodError (undefined method `headers_names' for DeviseTokenAuth:Module)

### ISSUE THREAD

**Issue by neilhanekom** [lynndylanhurley/devise_token_auth#684]
After Succesfull Email Authentication Confirmation I get and a 302 redirect requestand it goes to back to sign_up route with a account_confirmation_success as true. Which is following the Email registration flow as described in ng-token_auth docs. However when it comes to built_auth_header method in the user.rb file under conerns, I get the following:

 **

> NoMethodError (undefined method `headers_names' for DeviseTokenAuth:Module):
>   app/models/devise_token_auth/concerns/user.rb:200:in `build_auth_header'
>   app/models/devise_token_auth/concerns/user.rb:180:in `create_new_auth_token'

**

Why would this happen.??

**Comment by neilhanekom** [comment]
This error happens when using version 0.1.37. I have updated to version 0.1.38 and all seems to be working now.

Closing Issue.
